### ISSUE TITLE
DPI Control

### ISSUE THREAD

**Issue by abart27** [raphipod/Blade#2]
Add a DPI slider or similar for controlling the DPI on mouse

**Comment by raphipod** [comment]
Hello @Aurumaker72, and thanks for your suggestion! Although I don't have a Razer mouse at hand (only a keyboard), I will add this in the next stable release 0.30!

If you want, I could send you a pre-release build for testing purposes when the time is right.

**Comment by raphipod** [comment]
Hello @Aurumaker72, thanks for that idea! Unfortunately, due to the Colore API not supporting DPI changes (only colors & patterns), I can't implement this into my application.
